source("code/03_SDM import data.R")
rm(list = ls())
source("code/04_blockCV.R")
rm(list = ls())
source("code/05_SDM MaxEnt.R")
rm(list = ls())
source("code/06_SDM ensembles.R")
rm(list = ls())
source("code/07_prepare results for extraction.R")
rm(list = ls())

